### ISSUE TITLE
Further Optimisations

### ISSUE THREAD

**Issue by marcoherbst** [LitterBugCam/LitterDetection#14]
We suspect that there are many optimisations that could be made in the Matrix Operations:

- Sobel
- Blur
- Canny
- Resize()
- CvtColor()
- CartToPolar()
- Accumulation operator ()

Possible Solutions:
- Parallelisation
- GPU Optimisation

**Comment by elyas20** [comment]
Issue transffered to : https://github.com/LitterBugCam/Litterbug-docker
